version: "3.9"

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: secret_stash
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

networks:
  default:
    name: secret_stash_network
