server.port: 8080

app:
  jwt:
    expiration-in-ms: 180000
    secret: ${JWT_SECRET}

  rate-limiter:
    capacity: 50
    replenish-rate: 10
    replenish-in-seconds: 1

spring:
  application.name: Secret Stash

  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  liquibase:
    change-log: classpath:db/db.changelog-master.xml
    enabled: true